# Generated by Django 3.1 on 2020-08-25 00:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(default='NORMAL_USER', max_length=11)),
                ('home_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('job_title', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('blog', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('login_session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_social_signup', models.SmallIntegerField(default=0)),
                ('social_type', models.CharField(blank=True, max_length=9, null=True)),
                ('social_id', models.CharField(blank=True, max_length=250, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.Rename_Image_User)),
                ('user_image_thumb', models.TextField(blank=True, null=True)),
                ('user_token', models.CharField(blank=True, max_length=250, null=True)),
                ('is_verified', models.SmallIntegerField(default=0)),
                ('is_blocked', models.SmallIntegerField(default=0)),
                ('is_deactivated', models.SmallIntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('is_account_closed', models.SmallIntegerField(blank=True, null=True)),
                ('account_closed_datetime', models.DateTimeField(blank=True, null=True)),
                ('account_close_type', models.CharField(blank=True, max_length=150, null=True)),
                ('account_close_reason', models.TextField(blank=True, null=True)),
                ('stripe_user_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
